### ISSUE TITLE
Is it Upgrade or a Downgrade

### ISSUE THREAD

**Issue by Hasnain12340** [STForScratch/Scatt#1]
The new Update has no /help removed many functions that people were used to and the server was made fully for the old version not new without old features some text channels has no meaning because of it hope this'll be okay in future and i use autocode for making bots so if you agree with that i might help.. I LOVE SCATT and i want him

**Comment by rgantzos** [comment]
It's by far an upgrade. There are a ton of new features, including records and Scatt is just faster overall. Less downtime, counting is back, we have better XP, Scatt has logs and automatically gives people roles, the server info is better, and much, much more.
